### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by m93a** [chhu/gnuplot-JS#3]
Hello,
This is cool, I can definitely make use of gnuplot in browser!
But you don't mention any copyright… I know that gnuplot orders that you publish the changes in source as a patch, but it doesn't put any restrictions on the actual license. Also, none of gnuplot's rules aplies to the API which you wrote in JavaScript. Would you please consider adding a license to this project (favourably MIT), so that I could properly attribute you instead of recompiling gnuplot and rewriting the API pretending like I've never seen your project? 😉
Thanks a lot

**Comment by chhu** [comment]
Agreed. ;)
Have fun!
